server:
  port: 8083

spring:
  application:
    name: ordermanage
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  datasource:
    url: jdbc:mysql://localhost:3306/rabbitmq?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    virtual-host: rabbitmq
    listener:
      simple:
        acknowledge-mode: manual